<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Revoa.Abstractions\Revoa.Abstractions.csproj" />
    <ProjectReference Include="..\Revoa.IntegrationContracts\Revoa.IntegrationContracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Minio" Version="7.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="2.28.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
